title: "DevQuest"
description: "Connecting ideas to solutions, one problem at a time!"
theme: null
remote_theme: just-the-docs/just-the-docs

url: "https://shreshta001.github.io"
baseurl: ""  # Keep this blank for username.github.io repo

# Optional extras
color_scheme: light  # or dark

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
