# Site settings
title: "My Documentation Site"
description: "Awesome docs powered by Just the Docs"
baseurl: ""  # the subpath of your site, e.g. /docs (leave empty for root)
url: "https://yourusername.github.io" # your GitHub Pages URL or your domain

# Use Just the Docs remote theme
remote_theme: pmarsceill/just-the-docs

# Build settings
markdown: kramdown
theme: null # needed because we use remote_theme instead
plugins:
  - jekyll-remote-theme

# Just the Docs settings
just_the_docs:
  # Logo shown in the header
  logo: "/assets/images/logo.png"  # optional, add your logo path or remove line
  # Repository link for edit button and GitHub links
  repository_url: "https://github.com/yourusername/your-repo"
  repository_branch: "main"
  show_edit_link: true
  # Navigation sidebar items (optional, you can override in _data/navigation.yml)
  nav:
    - title: "Home"
      url: /
    - title: "Getting Started"
      url: /getting-started/
    - title: "API Reference"
      url: /api-reference/
    - title: "About"
      url: /about/

# Exclude unnecessary files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalinks for nice URLs
permalink: pretty
