title: DevQuest
description: Driven to elevate visiosn tthrough quest
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

author:
  name: "SSM"
  email: "yesyesem22@gmail.com"
  
minimal_mistakes_skin: air

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
