title: "APS Portfolio"
description: "Documentation powered by Just the Docs"
url: "https://shreshta001.github.io"
baseurl: ""

remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme
